[server]
headless = true
runOnSave = false

[client]
toolbarMode = "minimal"
showErrorDetails = true

[browser]
gatherUsageStats = false
[server]
headless = true
enableCORS = false

[ui]
hideTopBar = false
