page_title = "Vendors Directory"
page_max_width_px = 99999
sidebar_state = "collapsed"

# Column labels — start simple; you can change anytime
READONLY_COLUMN_LABELS = { business_name = "Provider" }
ADMIN_COLUMN_LABELS    = { business_name = "Provider" }

# Admin password gate
ADMIN_PASSWORD = "CHANGE-THIS-TO-A-STRONG-PASSWORD"

# Turso (libSQL) remote DB
TURSO_DATABASE_URL = "sqlite+libsql://vendors-prod-mrbookend.aws-us-west-2.turso.io?secure=true"
TURSO_AUTH_TOKEN   = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicm8iLCJpYXQiOjE3NTk5MTczMTgsImlkIjoiMGUxNDUwZmItN2ViMS00ZjI4LWFmYzUtMmQzNjRiYzgwNGE1IiwicmlkIjoiNzRlYzNkMDAtZjlmZC00YzNlLWExMDEtZmNkNjczNWZkMWI2In0.x4owcU0za_lwB1-j0ZQ9lWyM8ub_OVNQtFrvsxbGsqgw-cNrYWJ75MMDebHpZprIH0GrjvVVrqHONngLPYu4Cw"
